# version: '3.8'

services:
  app:
    build:
      context: ./asset-backend
    container_name: asset_app
    ports:
      - "8000:8000"
    volumes:
      - ./asset-backend:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: asset_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: asset_db
      MYSQL_USER: asset_user
      MYSQL_PASSWORD: asset_pass
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: asset_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: asset_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

volumes:
  db_data:
